base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('password_manager.urls')),
    path('', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

password_manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.WebsiteList.as_view(), name='home'),
    path('related-passwords/', views.same_password, name='same_passwords'),
    path('add-password/', views.add_password, name='add_password'),
    path('edit-password/<int:pk>/', views.edit_password, name='edit_password'),
    path('delete-password/<int:pk>/', views.DeletePassword.as_view(), name='delete_password'),
]

password_manager/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .encryption import decrypt


class Website(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='websites')
    link = models.URLField()
    
    # def save(self, *args, **kwargs):
    #     if (self.website).startswith('http://'):
    #         self.website = (self.website).replace('http://', 'https://')
    #     super(Website, self).save(*args, **kwargs)
    
    class Meta:
        ordering = ['-link']
        unique_together = 'user', 'link'
    
    def __str__(self):
        return self.link


class SiteDetail(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='details') 
    website = models.ForeignKey(Website, on_delete=models.CASCADE, related_name='details')
    username = models.CharField(max_length=50, blank=True)
    password = models.CharField(max_length=50)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-updated_at',)
        unique_together = 'website', 'username', 'password'
    
    def decrypt_password(self):
        return decrypt(self.password)
    
    def __str__(self):
        return self.username

password_manager/forms.py
from tkinter import Widget
from django import forms
from .models import Website, SiteDetail


class AddPasswordForm(forms.ModelForm):
    
    class Meta:
        model = SiteDetail
        fields = ('username', 'password')
            


class AddSiteForm(forms.ModelForm):
    
    class Meta:
        model = Website
        fields = ('link',)
        
        widgets = {
            'link': forms.TextInput(),
        }

password_manager/views.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from .encryption import encrypt, decrypt
from .forms import AddPasswordForm, AddSiteForm
from .models import SiteDetail, Website


class WebsiteList(LoginRequiredMixin, generic.ListView):
    model = Website
    context_object_name = 'websites'

    def get_queryset(self):
        """
        Return website only if website has details,
        and delete those without details.
        """
        websites = Website.objects.filter(user=self.request.user)
        websites_with_details = []
        for website in websites:
            website_details = website.details.all()
            if website_details.count() > 0:
                websites_with_details.append(website.id)
            else:
                Website.objects.get(id=website.id).delete()

        return Website.objects.filter(id__in=websites_with_details)


def edit_password(request, pk): 
    site_detail = SiteDetail.objects.get(id=pk)
    if request.method == 'POST':
        password_form = AddPasswordForm(instance=site_detail, data=request.POST)

        if password_form.is_valid():
            site_password = password_form.save(commit=False)
            site_password.password = encrypt(site_password.password)
            password_form.save()
            return redirect(reverse('manager:home'))
            
    else:
        password_form = AddPasswordForm(
            instance=SiteDetail(
                username=site_detail.username,
                password=decrypt(site_detail.password)
            )
        )

    context = {'form': password_form}
    return render(request, 'password_manager/edit_password.html', context)


class DeletePassword(LoginRequiredMixin, generic.DeleteView):
    model = SiteDetail
    template_name = 'password_manager/delete_password.html'
    success_url = reverse_lazy('manager:home')


@login_required
def same_password(request):
    """
    accounts with same password
    """    
    user = request.user
    site_password = user.details.all()
    passwords = {}

    for details in site_password:
        passwords.setdefault(details.password, []).append([details.username, details.website])

    same_password = {}
    for password, sites in passwords.items():
        if len(sites) > 1:
            same_password.setdefault(password, sites)

    context = {
        'sites': same_password,
    }

    return render(request, 'password_manager/related_password.html', context)


@login_required
def add_password(request):
    if request.method == 'POST':
        weblink_form = AddSiteForm(request.POST)
        password_form = AddPasswordForm(request.POST)

        if weblink_form.is_valid() and password_form.is_valid():
            website_link = weblink_form.save(commit=False)
            site_password = password_form.save(commit=False)

            website_link.user = request.user
            site_password.user = request.user
            site_password.password = encrypt(site_password.password)

            try:
                site_password.website = Website.objects.get(user=request.user, link=website_link)
            except:
                site_password.website = weblink_form.save()

            site_password.save()

        return redirect(reverse('manager:home'))

    else:
        weblink_form = AddSiteForm()
        password_form = AddPasswordForm()

    context = {
        'weblink_form': weblink_form,
        'password_form': password_form,
    }
    return render(request, 'password_manager/add_password.html', context)

password_manager/templates/password_manager/add_password.html
{% extends "main.html" %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    {{weblink_form.as_p}}
    {{password_form.as_p}}
    <input type="submit" value="Save">
</form>

{% endblock %}

password_manager/templates/password_manager/delete_password.html
{% extends "main.html" %}
{% block content %}

    <form class='edit_delete_form' method="POST" action="">
        {% csrf_token %}
        <p>are you sure you want to delete {{object_list.title}} ??</p>
        <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
        <input value="confirm" type="submit" />
    </form>

{% endblock content %}

password_manager/templates/password_manager/edit_password.html
{% extends "main.html" %}
{% block footer %}<!---->{% endblock %}
{% block title %}Edit Post{% endblock %}
{% block content %}

<h1>Edit Your {{title.capitalize}}</h1>
 <form  class='edit_delete_form' method="POST" enctype="multipart/form-data">{% csrf_token %}
        {{ form.media }}
        {{ form.as_p}}
        <input type="submit" value="Edit {{title}}">
    </form>
{% endblock %}

password_manager/templates/password_manager/related_password.html
{% extends "main.html" %}

{% block content %}

<div class="container-md mt-5">
    {% if sites %}
        <h1 class="display-6">Why use one password for mutiple sites 🥴?</h1>
        <p class="lead">Change it please!</p>
        {% for password, details in sites.items %}
            <div class="border rounded-3 align-items-center row p-3 my-4">
                <h6 class="col-lg-9 col-md-9 col-sm-8"><span class="text-secondary">password:</span> <b><i>{{password}}</i></b></h6>
                <h6 class="col-lg-2 col-md-2 col-sm-2">{{details.count}}</h6>

                <button class="btn btn-primary col-lg-1 col-md-1 col-sm-2 more_less" data-bs-toggle="collapse"
                    data-bs-target="#c{{website.id}}" role="button" aria-expanded="false"
                    aria-controls="c{{website.id}}">view</button>
                {% for name_site in details %}
                    <div class="collapse mt-3" id="c{{website.id}}">
                        <div class="card card-body">
                            <p>username : <b><i>{{ name_site.0 }}</i></b></p>
                            <p>website : <b><i>{{ name_site.1 }}</i></b></p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% endfor %}
    {% else %}
        <h2>Not Available</h2>
    {% endif %}
</div>

{% endblock %}

password_manager/templates/password_manager/website_list.html
{% extends "main.html" %}
{% load static %}

{% block content %}

<div class="container-md mt-5">
    {% if websites %}
        {% if user.first_name %}
            <h1 class="display-6">Welcome {{user.first_name.capitalize}},</h1>
        {% else %}
            <h1 class="display-6"><b><i>{{user.username}}'s</i></b> <span style="color: gray;">dashboard</span></h1>
        {% endif %}
        
        <form class="d-flex mt-5" role="search">
            <input class="form-control form-control-lg me-2" type="search" placeholder="Search sites..." aria-label="Search">
            <button type="submit" class="btn btn-lg btn-outline-warning">Search</button>
        </form>
        {% for website in websites %}
            <div class="row border border-2 align-items-center rounded-3 my-4 p-3">
                <h6 class="col-lg-8 col-md-8 col-sm-8">{{website}}</h6>
                <h6 class="col-lg-2 col-md-2 col-sm-2">{{website.details.count}}</h6> <!-- d-lg-block d-md-block d-sm-none -->
                <div class="col-lg-2 col-md-2 col-sm-2">
                    <button class="btn btn-primary more_less w-100" data-bs-toggle="collapse"
                    data-bs-target="#c{{website.id}}" role="button" aria-expanded="false" aria-controls="c{{website.id}}">view</button>
                </div>

                {% with details=website.details.all %}
                {% for detail in details %}
                    <div class="collapse mt-3" id="c{{website.id}}">
                        <div class="card card-body">
                            <div class="row">
                                <div class="col-lg-8 col-sm-12">
                                    <p>username: <i><b>{{detail.username}}</b></i></p>
                                    <p>password: <i><b>{{detail.decrypt_password}}</b></i></p>
                                </div>

                                <div class="col-lg-2 col-sm-12 my-2">
                                    <a href="{% url 'manager:edit_password' detail.pk %}" class="btn btn-outline-dark w-100">Edit</a>
                                </div>

                                <div class="col-lg-2 col-sm-12 my-2">
                                    <a href="{% url 'manager:delete_password' detail.pk %}" class="btn btn-outline-danger w-100">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% endwith %}
            </div>
        {% endfor %}

        <a href="{% url 'manager:add_password' %}" class="btn btn-warning mx-auto">Add Password +</a>
    {% else %}
        <div class="container justify-content-center">
            <h1 class="text-center m-auto">No Sites Available!</h1>
            <img src="{% static 'images/waves.png' %}" class="w-50 h-50 my-2 img-fluid">
            <div>
                <a class="btn btn-lg btn-warning rounded-pill" href="{% url 'manager:add_password' %}">Add Details +</a>
            </div>
        </div>
    {% endif %}
</div>

{% endblock %}