accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit, name='edit_profile'),
    path('delete-account/<str:pk>/', views.DeleteAccountView.as_view(), name='delete_account'),
    path('', include('django.contrib.auth.urls')),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('password_manager.urls')),
    path('', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    avatar = models.ImageField(default='users/default_profile_photo.svg', upload_to='users/%Y/%m/%d/')

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)
        

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        # exclude = ('GENDER_CHOICES', 'user')

accounts/views.py
from django.shortcuts import render

from .models import Profile
from django.urls import reverse
from .forms import UserRegistrationForm
from django.views.generic import DeleteView
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import UserEditForm, ProfileEditForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


def signup(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            user_form.save()
            Profile.objects.create(user=new_user)
            context = {'new_user': new_user}
            return render(request, 'accounts/register_done.html', context)
    else:
        user_form = UserRegistrationForm()

    context = {'user_form': user_form}
    return render(request, 'accounts/register.html', context)


@login_required
def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(
            instance=request.user.profile, data=request.POST, files=request.FILES)

        if profile_form.is_valid() and user_form.is_valid():
            profile_form.save() and user_form.save()

        return redirect(reverse('accounts:profile'))

    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)

    context = {'user_form': user_form, 'profile_form': profile_form}
    return render(request, 'accounts/edit.html', context)


class DeleteAccountView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'accounts/delete.html'
    success_url = '/login'

def profile(request):
    context = {}
    return render(request, 'accounts/profile.html', context)

accounts/templates/accounts/delete.html
{% extends "main.html" %}
{% block content %}

    <form class='edit_delete_form' method="POST" action="">
        {% csrf_token %}
        <p>are you sure you want to delete {{object_list.title}} ??</p>
        <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
        <input value="confirm" type="submit" />
    </form>

{% endblock content %}

accounts/templates/accounts/edit.html
{% extends "main.html" %}
   {% block title %}Edit your account{% endblock %}
{% block content %}
     <h1>Edit your account</h1>
     <p>You can edit your account using the following form:</p>
     <form method="post" enctype="multipart/form-data">
       {{ user_form.as_p }}
       {{ profile_form.as_p }}
       {% csrf_token %}
       <p><input type="submit" value="Save changes"></p>
     </form>
   {% endblock %}

accounts/templates/accounts/profile.html
{% extends "main.html" %}
{% block title %} Dashboard{% endblock %}
{% load static %}

{% block content %}

<div class="container">
    <h1 style="font-family: Inter, sans-serif;">PROFILE</h1>

    <div class="row row-cols-1 row-cols-lg-2 row-cols-md-1">
        <div class="col">
            <figure class="py-5" style="min-height: 420px;">
                <!-- <img src="{{request.user.avatar.url}}" alt="profile-photo" class="avatar"> -->
                <img src="{{request.user.profile.avatar.url}}" class="img-fluid rounded-5 mx-atuo">
            </figure>

            <div class="px-5">
                <h2><b>@{{request.user.username}}</b></h2>
                <span><b>{{request.user.first_name}} {{request.user.last_name}}</b></span>
            </div>
        </div>

        <div class="col p-5">
            <div class="row">
                <a class='btn btn-lg border border-2 border-warning my-2' 
                    href="{% url 'accounts:edit_profile' %}">Edit your profile</a>
                <a class='btn btn-lg border border-2 border-warning my-2'
                    href="{% url 'accounts:edit_profile' %}">Manage Passwords</a>
                <button class='btn btn-lg btn-disabled border border-2 border-warning my-2' 
                    href="" disabled>Invite a friend</button>
                <a class='btn btn-lg btn-danger my-2' 
                    href="{% url 'accounts:delete_account' request.user.pk %}">Delete account</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/register.html
{% extends "main.html" %}
   {% block title %}Create an account{% endblock %}
   {% block content %}
     <h1>Create an account</h1>
     <p>Please, sign up using the following form:</p>
     <form method="post">
       {{ user_form.as_p }}
       {% csrf_token %}
       <p><input type="submit" value="Create my account"></p>
     </form>
   {% endblock %}

accounts/templates/accounts/register_done.html
{% extends "main.html" %}
   {% block title %}Welcome{% endblock %}
   {% block content %}
     <h1>Welcome {{ new_user.first_name }}!</h1>
     <p>Your account has been successfully created. Now you can <a
   href="{% url 'accounts:login' %}">log in</a>.</p>
   {% endblock %}