accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('edit-profile/', views.edit, name='edit_profile'),
    path('delete-account/<str:pk>/', views.DeleteAccountView.as_view(), name='delete_account'),
    path('', include('django.contrib.auth.urls')),
]

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('password_manager.urls')),
    path('', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

password_manager/urls.py
from django.urls import path
from . import views

app_name = 'manager'

urlpatterns = [
    path('', views.WebsiteList.as_view(), name='home'),
    path('related-passwords/', views.same_password, name='same_passwords'),
    path('add-password/', views.add_password, name='add_password'),
    path('edit-password/<int:pk>/', views.edit_password, name='edit_password'),
    path('delete-password/<int:pk>/', views.DeletePassword.as_view(), name='delete_password'),
]

password_manager/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .encryption import decrypt


class Website(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='websites')
    link = models.URLField()
    
    # def save(self, *args, **kwargs):
    #     if (self.website).startswith('http://'):
    #         self.website = (self.website).replace('http://', 'https://')
    #     super(Website, self).save(*args, **kwargs)
    
    class Meta:
        ordering = ['-link']
        unique_together = 'user', 'link'
    
    def __str__(self):
        return self.link


class SiteDetail(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='details') 
    website = models.ForeignKey(Website, on_delete=models.CASCADE, related_name='details')
    username = models.CharField(max_length=50, blank=True)
    password = models.CharField(max_length=50)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-updated_at',)
        unique_together = 'website', 'username', 'password'
    
    def decrypt_password(self):
        return decrypt(self.password)
    
    def __str__(self):
        return self.username

password_manager/forms.py
from tkinter import Widget
from django import forms
from .models import Website, SiteDetail


class AddPasswordForm(forms.ModelForm):
    
    class Meta:
        model = SiteDetail
        fields = ('username', 'password')
            


class AddSiteForm(forms.ModelForm):
    
    class Meta:
        model = Website
        fields = ('link',)
        
        widgets = {
            'link': forms.TextInput(),
        }

password_manager/views.py
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy

from .encryption import encrypt, decrypt
from .forms import AddPasswordForm, AddSiteForm
from .models import SiteDetail, Website


class WebsiteList(LoginRequiredMixin, generic.ListView):
    model = Website
    context_object_name = 'websites'

    def get_queryset(self):
        """
        Return website only if website has details,
        and delete those without details.
        """
        websites = Website.objects.filter(user=self.request.user)
        websites_with_details = []
        for website in websites:
            website_details = website.details.all()
            if website_details.count() > 0:
                websites_with_details.append(website.id)
            else:
                Website.objects.get(id=website.id).delete()

        return Website.objects.filter(id__in=websites_with_details)


def edit_password(request, pk): 
    site_detail = SiteDetail.objects.get(id=pk)
    if request.method == 'POST':
        password_form = AddPasswordForm(instance=site_detail, data=request.POST)

        if password_form.is_valid():
            site_password = password_form.save(commit=False)
            site_password.password = encrypt(site_password.password)
            password_form.save()
            return redirect(reverse('manager:home'))
            
    else:
        password_form = AddPasswordForm(
            instance=SiteDetail(
                username=site_detail.username,
                password=decrypt(site_detail.password)
            )
        )

    context = {'form': password_form}
    return render(request, 'password_manager/edit_password.html', context)


class DeletePassword(LoginRequiredMixin, generic.DeleteView):
    model = SiteDetail
    template_name = 'password_manager/delete_password.html'
    success_url = reverse_lazy('manager:home')


@login_required
def same_password(request):
    """
    accounts with same password
    """    
    user = request.user
    site_password = user.details.all()
    passwords = {}

    for details in site_password:
        passwords.setdefault(details.password, []).append([details.username, details.website])

    same_password = {}
    for password, sites in passwords.items():
        if len(sites) > 1:
            same_password.setdefault(password, sites)

    context = {
        'sites': same_password,
    }

    return render(request, 'password_manager/related_password.html', context)


@login_required
def add_password(request):
    if request.method == 'POST':
        weblink_form = AddSiteForm(request.POST)
        password_form = AddPasswordForm(request.POST)

        if weblink_form.is_valid() and password_form.is_valid():
            website_link = weblink_form.save(commit=False)
            site_password = password_form.save(commit=False)

            website_link.user = request.user
            site_password.user = request.user
            site_password.password = encrypt(site_password.password)

            try:
                site_password.website = Website.objects.get(user=request.user, link=website_link)
            except:
                site_password.website = weblink_form.save()

            site_password.save()

        return redirect(reverse('manager:home'))

    else:
        weblink_form = AddSiteForm()
        password_form = AddPasswordForm()

    context = {
        'weblink_form': weblink_form,
        'password_form': password_form,
    }
    return render(request, 'password_manager/add_password.html', context)

password_manager/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Password Manager{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
</head>

<body>

    {% block navbar %}
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'manager:home' %}">PM</a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
                aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'manager:home' %}">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'manager:same_passwords' %}">Manage</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'accounts:profile' %}">Profile</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>

                {% if request.user.is_authenticated %}
                    <form class="d-flex mx-2" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search Sites" aria-label="Search">
                        <button type="submit" class="btn btn-outline-warning">Search</button>
                    </form>

                    <a class="btn btn-warning rounded-pill d-flex mx-2" href="{% url 'manager:add_password' %}">Add password +</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% endblock %}

    
    <!-- content in other pages -->
    {% block content %}{% endblock %}

</body>

password_manager/templates/related_password.html
{% if sites %}
    <h1 style="text-align: center;">Why use one password for mutiple sites 😒?</h1>
    {% for password, details in sites.items %}
        <div style="border: 2px solid black; margin:30px;padding:20px;">
            <p><h4>{{ password }}</h4></p>
            <hr>
            {% for name_site in details %}
                <p>user_name : <b><i>{{ name_site.0 }}</i></b></p>
                <p>web_site : <b><i>{{ name_site.1 }}</i></b></p>
                <hr>
            {% endfor %}
        </div>
    {% endfor %}
{% else %}
        <h2>Not Available</h2>
{% endif %}